FROM quay.io/forem/forem:latest

# Веб-служба Rails, которая запускает основное приложение.
# We create the localimages/uploads symlink to enable serving images from 
# the Rails server in production. 
# See https://github.com/forem/forem/issues/13307 for more details.
# RUN mkdir /opt/apps/forem/public/localimages
# RUN ln -s /opt/apps/forem/public/uploads/ /opt/apps/forem/public/localimages/uploads

ADD ./scripts scripts/
ADD ./scripts opt/apps/forem/

ENTRYPOINT ["bash", "./scripts/rails.sh"]

ENTRYPOINT ["./scripts/entrypoint.sh"]

CMD ["bash", "-c", "./scripts/entrypoint.sh bootstrap]
